# ベースイメージ
FROM python:3.11-slim

# コンテナ内作業ディレクトリ
WORKDIR /workspaces/愛ちゃんポイント収集

# ホストの requirements.txt をコピー＆インストール
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# ソースコードをコピー
COPY . .

# デフォルトのコマンド
CMD ["bash"]